pull_request_rules:
  - name: Automatic merge on approval
    conditions:
    - approved-reviews-by=@fedora-iot/zezere
    - label=automerge
    - status-success=DCO
    - status-success=build
    - status-success=integration_test
    - status-success=packit/testing-farm-fedora-rawhide-x86_64
    actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
  - name: Automatic merge on test pass by maintainer
    conditions:
    - author=@fedora-iot/zezere
    - label=automerge
    - status-success=DCO
    - status-success=python_test
    - status-success=integration_test
    - status-success=packit/testing-farm-fedora-rawhide-x86_64
    actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
